### Common

server:
  port: 8081

spring:
  application:
    name: VirtualDeviceSimulator
  profiles:
    active: dev
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    root: INFO

virtualdevices:
  mqtt:
    broker:
      url: tcp://localhost:1883
    clientId: VirtualGateway

---

### Dev profile

spring:
  profiles: dev

logging:
  level:
    com.unloadbrain: DEBUG

---

### Prod profile

spring:
  profiles: prod

logging:
  level:
    com.unloadbrain: INFO

---

### Integration test profile

spring:
  profiles: it
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

---

### docker profile

spring:
  profiles: docker
virtualdevices:
  mqtt:
    broker:
      url: tcp://mosquitto:1883